#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a Steam desktop='^4'
bspc rule -a dota2 desktop='^5' follow=on
bspc rule -a eu4 desktop='^5' follow=on
