#!/bin/bash

alias sn='shutdown now'
alias r='reboot'
alias v='vim'
alias en='emacs -nw'
alias em='emacs'
alias ku='kill -u kyziak'
#alias upd='sudo pacman -Syyu'
alias upd='sudo apt-get update && sudo apt-get upgrade'
alias rbash='source ~/.bashrc'

# Aliases for git
alias gs='git status'
alias gcm='git commit -m'
alias gp='git push'
alias gt='git pull'
alias gd='git diff'
alias ga='git add'
alias gl='git log'
alias gbm='git branch -M main'

#alias battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0'

#Python aliases
alias py='python3'
alias activate='source .venv/bin/activate'
alias runserver='./manage.py runserver'

# aliases for ls 
alias ll='ls -alF'
alias la='ls -a'
alias l='ls -CF'
